version: '3'
services:
  # rawcms:
    # build: .
    # ports:
    # - "54321:54321"   
    # links:
    # - mongo
    # environment:
    # - MongoSettings__ConnectionString=mongodb://mongo:27017/rawCms
    # - PORT=54321
    # - ASPNETCORE_ENVIRONMENT=Docker
  # mongo:
    # image: mongo
  elasticsearchtest:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9300:9200
